version: "3.7"
services:
  postgres_prod:
    container_name: spring_hateoas
    image: postgres:13.3
    environment: 
      POSTGRES_USER: hateoas
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"